const PAGING = {
  ADMIN: {
    TEN_ITEM_PER_PAGE: 10,
    TWENTY_FIVE_ITEM_PER_PAGE: 25,
    FIFTY_ITEM_PER_PAGE: 50,
    ONE_HUNDRED_ITEM_PER_PAGE: 100,
  },
  HOME: {
    TEN_ITEM_PER_PAGE: 10,
    TWENTY_FIVE_ITEM_PER_PAGE: 25,
    FIFTY_ITEM_PER_PAGE: 50,
    ONE_HUNDRED_ITEM_PER_PAGE: 100,
  },
};

export default PAGING;
